stages:
  - build
  - test

build:
  stage: build
  script:
    - 'npm --prefix src install'
    - 'npm run --prefix src build'

test:
  stage: test
  script:
    - 'npm --prefix src test'
  dependencies:
    - build